### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by htmlgod** [htmlgod/cpp-library-template#1]
- [ ] clangformat file
- [ ] clangformatter script
- [ ] fix whitespaces in source code
- [ ] add win support in cmake
- [ ] add debug and other flags to cmake (like optimization and etc)
